---
apiVersion: v1
kind: Namespace
metadata:
  name: sonatype
spec:
  finalizers:
  - kubernetes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonatype
  namespace: sonatype
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sonatype
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sonatype
        version: v1
    spec:
      containers:
      - image: sonatype/nexus3:3.16.2
        imagePullPolicy: Always
        name: nexus3
        resources: {}
      - image: sonatype/nexus-iq-server:1.65.0
        imagePullPolicy: Always
        name: iq-server
        resources: {}
      restartPolicy: Always
